@startuml

class EdsBasicDeliveryStatus {
<<EHMI Delivery Status for ikke patientrelaterede meddelelser>>
===
    + Agent ehmiSender
    + Agent ehmiReceiver
---
    + Observer eerDevice
---
    + Entity ehmiMessage
        + EntityDetail ehmiMessageType
        + EntityDetail ehmiMessageVersion
---
    + Entity ehmiTransportEnvelope
        + EntityDetail ehmiTransportEnvelopeType
        + EntityDetail ehmiTransportEnvelopeVersion
---
    + Entity * insert ehmiOrigMessage-HCO

        + EntityDetail ehmiMessageType
        + EntityDetail ehmiMessageVersion
---
    + Entity ehmiOrigTransportEnvelope
        + EntityDetail ehmiTransportEnvelopeType
        + EntityDetail ehmiTransportEnvelopeVersion
}

AuditEvent <-- EdsBasicDeliveryStatus

@enduml