@startuml

class EdsBasicDeliveryStatus {
    + Type ehmiMessaging
    + Agent ehmiSender
    + Agent ehmiReceiver
    + Observer eerDevice
    + Entity ehmiMessage
        + EntityDetail ehmiMessageType
        + EntityDetail ehmiMessageVersion
    + Entity ehmiTransportEnvelope
        + EntityDetail ehmiTransportEnvelopeType
        + EntityDetail ehmiTransportEnvelopeVersion
    + Entity ehmiOrigMessage
        + EntityDetail ehmiMessageType
        + EntityDetail ehmiMessageVersion
    + Entity ehmiOrigTransportEnvelope
        + EntityDetail ehmiTransportEnvelopeType
        + EntityDetail ehmiTransportEnvelopeVersion
}

class EdsPatientDeliveryStatus {
    + Type ehmiMessaging
    + Agent ehmiSender
    + Agent ehmiReceiver
    + Observer eerDevice
    + Entity Patient
    + Entity ehmiMessage
        + EntityDetail ehmiMessageType
        + EntityDetail ehmiMessageVersion
    + Entity ehmiTransportEnvelope
        + EntityDetail ehmiTransportEnvelopeType
        + EntityDetail ehmiTransportEnvelopeVersion
    + Entity ehmiOrigMessage
        + EntityDetail ehmiMessageType
        + EntityDetail ehmiMessageVersion
    + Entity ehmiOrigTransportEnvelope
        + EntityDetail ehmiTransportEnvelopeType
        + EntityDetail ehmiTransportEnvelopeVersion
}

AuditEvent <-- EdsBasicDeliveryStatus
EdsBasicDeliveryStatus <-- EdsPatientDeliveryStatus
@enduml